# Preface to {{< var ay >}} BM425 Workshop 1 {.unnumbered}

Welcome to the BM425 (Advanced Microbiology) workshop on SARS-CoV-2 genome analysis, for {{< var ay >}}.

This year is the first presentation of the workshop material in this format, and we would be very grateful to hear feedback [by email](mailto:{{< var admin.email >}}) or through the [GitHub repository Issues page]({{< var github.issues >}}).

## Overview

This workshop asks you to work through some bioinformatics exercises using the online service [`Galaxy`](https://usegalaxy.eu/), with [data](data.qmd) that we provide, to:

- assemble, annotate, and visualise the first SARS-CoV-2 genome isolated in Wuhan, in January 2020
- compare the genome of SARS-CoV-2 to that of an earlier coronavirus (SARS 2003)
- compare the genome of the first SARS-CoV-2 genome to that of an variant from later in the pandemic
- make a biological interpretation of your analysis, particularly of the spike (S) protein

::: { .callout-warning }
## Important Note

There is new material in this workshop that is not covered in lectures. **This material is examinable.**

Please take care to read the text in the expandable callout boxes, as well as that for the workshop activities, to be sure you have understood the topic and obtain full value from the exercises.
:::

## How To Move Through These Workshop Materials

On your first run through this workshop, you should read each page in turn, and carry out each activity. You can see what activities are involved in the navigation sidebar on the left hand side of this page.

As you complete each activity, you can use the arrows at the bottom of the page to move forward and backward. If you need to, you can use the navigation sidebar on the left to jump to a section, and you can use the search field at the top of the sidebar to find specific content.

Please work through the workshop steps in order and, if you get stuck, please ask one of the lecturers or demonstrators for help.

1. [Join the training session](join-session.qmd) at [https://usegalaxy.eu/join-training/bm425-workshop1-2024](https://usegalaxy.eu/join-training/bm425-workshop1-2024)
2. [Download the workshop data](download-data.qmd) to your computer
3. [Upload the workshop data](upload-data.qmd) to your Galaxy history
4. Prepare your sequencing read data for assembly
5. Assemble a genome from your sequencing data
6. Visualise your genome assembly
7. Annotate your assembly
8. Visualise your annotation
9. Map reads from your SARS-CoV-2 isolate to the SARS 2003 genome
10. Visualise the mapped reads using `JBrowse2`
11. Identify sequence variants (SNPs, Single Nucleotide Polymorphisms) between SARS-CoV-2 and SARS 2003
12. Use what you've learned to identify and interpret changes in the SARS-CoV-2 virus during the COVID-19 pandemic

## Useful Links

- Register an account at the Galaxy instance for training: [link](https://usegalaxy.eu/login/start?redirect=None)
- Join the workshop training group on Galaxy: [link](https://usegalaxy.eu/join-training/bm425-workshop1-2024)

## Learning Objectives

By the end of this workshop, students will be able to:

- understand and use the [Galaxy scientific workflow system](https://usegalaxy.eu/) (@Galaxy_Community2024-zi)
- recognise and use common sequencing data formats
- use common bioinformatics tools to:
  - assemble sequenced reads into a genome sequence
  - annotate features on an assembled genome sequence
  - map sequencing reads onto an assembled genome
  - carry out comparative genome analysis
  - visualise and interpret the results of genome annotation and analysis
  
## Assessment

::: { .callout-important }
There is a formative assessment on the [workshop MyPlace page](https://classes.myplace.strath.ac.uk/course/view.php?id=21676) that you should complete at the end of the workshop, to demonstrate you've earned your genomics wings (link below).

- [MyPlace formative quiz](https://classes.myplace.strath.ac.uk/mod/quiz/view.php?id=1295456)
:::

