# Workshop {#sec-workshop .unnumbered}

The chapters in this section of the site will lead you through each step of the workshop. Please work through these steps in order and, if you get stuck, please ask one of the lecturers or demonstrators for help.

1. Log in to your account at [https://usegalaxy.eu/](https://usegalaxy.eu/)
2. [Download the workshop data](download-data.qmd) to your computer
3. [Upload the workshop data](upload-data.qmd) to your Galaxy history
4. [Prepare your sequencing read data](trimmomatic.qmd) for assembly
5. [Assemble a genome](shovill.qmd) from your sequencing data
6. Visualise your genome assembly
7. [Annotate](prokka.qmd) your assembly
8. [Visualise](jbrowse.qmd) your annotation
9. [Map reads](bwamem.qmd) from your SARS-CoV-2 isolate to the SARS 2003 genome
10. Visualise the mapped reads using `JBrowse2`
11. [Identify sequence variants](snippy.qmd) (SNPs, Single Nucleotide Polymorphisms) between SARS-CoV-2 and SARS 2003
12. [Use what you've learned](instructions.qmd) to identify and interpret changes in the SARS-CoV-2 virus during the COVID-19 pandemic

